Add settings link to plugins page
rollbar/rollbar-php-wordpress pull request #109
Opened 2022-06-05 03:09 UTC by Brugman

## Description of the change

Adds a link to the Rollbar settings page on the plugins page. This way, after activation, you won't have to browse all menus, you just click the settings link and find out.

![2022-06-05-04-45-18](https://user-images.githubusercontent.com/2203813/172033284-688e5b79-2b01-4cff-8691-20518e53a608.jpg)

## Type of change

- New feature (non-breaking change that adds functionality)

## Related issues

None.

## Checklists

I'm not yet familiar with testing, I did test manually of course, and I'm on Windows. I hope you'll take this without testing, or can run tests on my behalf.

2022-06-06 20:01 UTC, danielmorell requested changes
This is definitely a helpful addition for users. Thank you @Brugman!

2022-06-06 20:01 UTC, danielmorell commented on src/Settings.php
> +        $args['page'] = 'rollbar_wp';
Creating an array using the `$array[key] = value;` syntax is discouraged see [Creating/modifying with square bracket syntax](https://www.php.net/manual/en/language.types.array.php#language.types.array.syntax.modifying).

The codebase uses the longhand `array(key => value);` syntax consistently. At some point we may switch to the short hand `[]` array constructors.

2022-06-07 01:06 UTC, Brugman commented
Awesome! I'll change the syntax. I copy pasted this and forgot to adapt it to the existing code style.

2022-06-07 10:48 UTC, danielmorell approved these changes
Perfect. Thanks!

2022-06-07 10:48 UTC, merged